namespace FooNamespace.Tests;
public class Boo_Tests
{
    [Fact]
    public void Method1()
    {
        Assert.Fail("autogenerated");
    }

    [Fact]
    public void Method2()
    {
        Assert.Fail("autogenerated");
    }
}